### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1129-1137: ordinal not in range(128)

### ISSUE THREAD

**Issue by swrite** [vergl4s/instarecon#3]
Hi , I run the code on ceotos7 , I have a mistake ， 

 `Traceback (most recent call last):
  File "/root/.pythonbrew/pythons/Python-2.7.10/bin/instarecon.py", line 4, in <module>
    __import__('pkg_resources').run_script('Instarecon==0.1.2', 'instarecon.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1490, in run_script
  File "/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/Instarecon-0.1.2-py2.7.egg/EGG-INFO/scripts/instarecon.py", line 308, in <module>
    
  File "/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/Instarecon-0.1.2-py2.7.egg/EGG-INFO/scripts/instarecon.py", line 101, in scan_targets
    
  File "/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/Instarecon-0.1.2-py2.7.egg/EGG-INFO/scripts/instarecon.py", line 122, in scan_host
    
  File "/root/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/Instarecon-0.1.2-py2.7.egg/EGG-INFO/scripts/instarecon.py", line 159, in scan_host_whois
    
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1129-1137: ordinal not in range(128)`

Do you know how to solve

**Comment by vergl4s** [comment]
Hey, I tried recreating it here but wasn't able to. I did however encounter some other problems related to a newer version of the ipwhois library. I updated the dependencies' versions on setup.py. See if you can reinstall Instarecon (by going ./setup.py install) and please tell me the results.

**Comment by swrite** [comment]
Thank you can reply me, I have just opened a centos7 x64 VPS, tried again, the error still exists  

[http://77fya2.com1.z0.glb.clouddn.com/_1.png](url)
[http://77fya2.com1.z0.glb.clouddn.com/2.png](url)
[http://77fya2.com1.z0.glb.clouddn.com/_33.png](url)
[http://77fya2.com1.z0.glb.clouddn.com/4.png](url)
[http://77fya2.com1.z0.glb.clouddn.com/5.png](url)

**Comment by vergl4s** [comment]
Thanks for the extra info. I was able to reproduce the issue and (hopefully) fix it. Can you try again with the latest version of instarecon?

**Comment by swrite** [comment]
It has been able to run normally, thanks
